// Mocks generated by Mockito 5.4.5 from annotations
// in mobile_be/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:mobile_be/services/teacher-service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TeacherService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeacherService extends _i1.Mock implements _i2.TeacherService {
  MockTeacherService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> login(
    String? email,
    String? password,
    String? for_type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
            for_type,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> getClass() => (super.noSuchMethod(
        Invocation.method(
          #getClass,
          [],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> getAllTeacher() => (super.noSuchMethod(
        Invocation.method(
          #getAllTeacher,
          [],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> getTeacherById(String? teacherId) => (super.noSuchMethod(
        Invocation.method(
          #getTeacherById,
          [teacherId],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> updateTeacheTeachNClass(
    String? teacherUid,
    List<dynamic>? classroom,
    String? subject,
    dynamic homeroomClassroom,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTeacheTeachNClass,
          [
            teacherUid,
            classroom,
            subject,
            homeroomClassroom,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> registerTeacher(
    String? name,
    String? email,
    String? password,
    String? teacherId,
    String? phoneNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerTeacher,
          [
            name,
            email,
            password,
            teacherId,
            phoneNumber,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> updateTeacherPhoto(
    String? teacherId,
    _i4.File? image,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTeacherPhoto,
          [
            teacherId,
            image,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
}
