name: mobile_be
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.4.0
  intl: ^0.19.0
  sqflite: ^2.3.0
  http: ^1.2.2
  file_picker: ^8.1.7
  shared_preferences: ^2.2.3
  image_picker: ^0.8.3
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  photo_view: ^0.14.0
  mime: ^2.0.0
  syncfusion_flutter_pdfviewer: ^28.1.33
  google_mobile_ads: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl_translation: ^0.20.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/l10n/
    - image/
