name: mobile_be
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.4.4
  intl: ^0.19.0
  sqflite: ^2.3.0
  http: ^1.2.2
  shared_preferences: ^2.2.3
  image_picker: ^0.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - image/
